#include <stdio.h>
#include <stdlib.h>
#include <syslog.h>

int main(int argc, char **argv){
    openlog("test", LOG_PID | LOG_PERROR | LOG_SYSLOG, 0);
    syslog(LOG_INFO, "This is a syslog test message generated by program '%s'n", argv[0]);
    closelog();
    return 0;
}
